### ISSUE TITLE
Clock bug

### ISSUE THREAD

**Issue by QuenMBar** [cs262fa18/Project#24]
Sometimes on first install the clock will jump to a random number.  Fix for know is manually uninstalling the app from your phone and then reinstalling it.

**Comment by twtduck** [comment]
When this happens, does it persist between sessions of the app?

If so, uploading the timedata.csv file from Android/data/edu.calvin.cs262.teama.timetracker/files/ would be very helpful.

**Comment by QuenMBar** [comment]
FIXED
